### ISSUE TITLE
About the Adjacency Matrix

### ISSUE THREAD

**Issue by JethroJC** [allenai/savn#15]
Hi,

Could you please tell me how to compute the adjacency matrix  for gcn baseline. Is the matrix extracted from Visual Genome or from the whole rooms?

Actually, I want to get the object relationships (e.g., the sink is next to the toilet) in a specific scene. However, I only find API to get the objects list in the scene with their centric coordinates. Because of the different scales of objects and coordinates of different rooms, I can not compute the connection relationship of the objects. Do you have any idea?

Thank you very much!

**Comment by mitchellnw** [comment]
Hey, it's from visual genome and not per room -- more details in [their paper](https://arxiv.org/abs/1810.06543)!
