### ISSUE TITLE
Question about hdf5 file

### ISSUE THREAD

**Issue by xjz89982** [allenai/savn#4]
I want to get the image so I downloaded the thor_offlline_data_with_images and followed the docs in h5py's website but there was no output. why? Did i made some mistake?
>import h5py
>f = h5py.File('images.hdf5', 'r')
>list(f.keys())

**Comment by xjz89982** [comment]
Sorry for bothering you, i've figured it out. The keys are stored in graph.json right?  :)

**Comment by mitchellnw** [comment]
No worries at all, glad it was resolved! Yes, the keys should be in `graph.json`.
