### ISSUE TITLE
Question about ai2thor version for offline data

### ISSUE THREAD

**Issue by xiaobaishu0097** [allenai/savn#5]
Hi,

I just found the script in the #3, but it seems that would be asserted at line 384 in offline_controller_with_small_rotation.py. 

Meanwhile, I could not understand the visible_object_map.json, some node in that file seems to be further than 1 meter from the target.

Thanks

**Comment by mitchellnw** [comment]
Sorry, I do not understand the first part of your question, do you mind explaining in more detail?

The `visible_object_map.json` contains a dictionary of items and lists of locations where those items are visible according to ai2thor.

We create it with this script:

```    
for scene in scenes:
    try:
        with open('{}/{}/metadata.json'.format(data_dir, scene), 'r') as f:
            metadata_list = json.load(f)

        visible_map = {}
        for k in metadata_list:
            metadata = metadata_list[k]
            for obj in metadata['objects']:
                if obj['visible']:
                    objId = obj['objectId']
                    if objId not in visible_map:
                        visible_map[objId] = []
                    visible_map[objId].append(k)
        
        with open('{}/{}/visible_object_map.json'.format(data_dir, scene), 'w') as f:
            json.dump(visible_map, f)
    except Exception as e:
        print(scene, e)
```

**Comment by xiaobaishu0097** [comment]
Thanks for your reply!
It is my problem for the misunderstanding questions, sorry for that.

1. When I run the script from #3 :
```
def search_and_save(in_queue):
    while not in_queue.empty():
        try:
            scene_name = in_queue.get(timeout=3)
        except:
            return
        c = None
        try:
            out_dir = os.path.join(<path-to-where-you-want-data-to-go>, scene_name)
            if not os.path.exists(out_dir):
                os.mkdir(out_dir)

            print('starting:', scene_name)
            c = ExhaustiveBFSController(
                grid_size=0.25,
                fov=90.0,
                grid_file=os.path.join(out_dir, 'grid.json'),
                graph_file=os.path.join(out_dir, 'graph.json'),
                metadata_file=os.path.join(out_dir, 'metadata.json'),
                images_file=os.path.join(out_dir, 'images.hdf5'),
                depth_file=os.path.join(out_dir, 'depth.hdf5'),
                grid_assumption=False)
            c.start()
            c.search_all_closed(scene_name)
            c.stop()
        except AssertionError as e:
            print('Error is', e)
            print('Error in scene {}'.format(scene_name))
            if c is not None:
                c.stop()
            continue
```
It always be asserted at line **384** in _offline_controller_with_small_rotation.py_ 
`assert next_state == next_state_guess
`

It seems that the agent is tricked in front of the fridge, cause the assertion error.


2. I thought the visible attribute of the object might be 1.5 meters according to the [https://ai2thor.allenai.org/documentation/concepts](url). In this case, should we modify the environment variable to the same as the paper?

Thanks

**Comment by mitchellnw** [comment]
Unfortunately the documentation and error are for the new AI2-THOR and I am not sure what the bug is -- are you able to use the scraped data? We tried to scrape it so that this would be easier, as we also had issues when initially scraping. Also feel free to raise an issue on the AI2-THOR repo if you are noticing strange behavior (e.g. the agent thinks it is moving forward but the fridge or something like it is confusing the agent).

One fix that you can try is calling `GetReachablePositions()` and make sure the agent is always in one of those positions.

**Comment by xiaobaishu0097** [comment]
Thanks for that, I have fixed this problem with your suggestions!

**Comment by xuai05** [comment]
Hello, when I call your search_and_save function, what is the cause of the following error? After the error occurs, the process becomes a zombie process, and the program cannot continue.

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "gen_ground_truth.py", line 39, in search_and_save
    c.start()
  File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/site-packages/ai2thor/controller.py", line 804, in start
    self.download_binary()
  File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/site-packages/ai2thor/controller.py", line 742, in download_binary
    os.rename(extract_dir, os.path.join(self.releases_dir(), self.build_name()))
OSError: [Errno 39] Directory not empty: '/home/ubuntu/.ai2thor/tmp/thor-201903131714-Linux64' -> '/home/ubuntu/.ai2thor/releases/thor-201903131714-Linux64'
